name: Daily Google SpreadSheet Update

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時(UTC)に実行
  workflow_dispatch: # 手動実行を可能にするトリガー

jobs:
  gss_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # 必要なPythonのバージョンを指定

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Set up GCP credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > scraping/credentials.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run scraping for fukuoka_major_station with Google SpreadSheet update
        # 主要駅。CSVを保存せずにGoogle Spreadsheetに反映する
        run: uv run python -m scraping fukuoka_major_station --skip-csv-storing
        env:
          GOOGLE_APPLICATION_CREDENTIALS: scraping/credentials.json
