name: Scrape and Commit

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の0時に実行
  workflow_dispatch:  # 手動実行を可能にするトリガー

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 必要なPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scrape.py
      run: python scrape.py

    - name: Create or switch to gh_actions branch
      run: |
        git fetch origin
        if git show-ref --verify --quiet refs/heads/gh_actions; then
          git checkout gh_actions
        else
          git checkout -b gh_actions
        fi

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add data/*.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update CSV data"
        git push origin gh_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}