name: Test Run Google SpreadSheet Update

on:
  workflow_dispatch: # 手動実行を可能にするトリガー

jobs:
  gss_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Read and write access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # 必要なPythonのバージョンを指定

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Set up GCP credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > scraping/credentials.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run scraping for main_disttricts with Google SpreadSheet update
        run: uv run python -m scraping main_disttricts --skip-csv-storing --test-run
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GOOGLE_SPREAD_SHEET_KEY: ${{ secrets.GOOGLE_SPREAD_SHEET_KEY }}
