name: Weekly CSV Update

on:
  schedule:
    - cron: "0 0 * * 1" # 毎週月曜日の0時に実行
  workflow_dispatch: # 手動実行を可能にするトリガー

jobs:
  csv_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.10" # 必要なPythonのバージョンを指定

      - name: Install dependencies
        run: |
          cd scraping
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up GCP credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > scraping/credentials.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run scraping for fukuoka_convinient with CSV storage only
        # 人気駅。CSVを保存するが、GoogleSpreadSheetには反映しない
        run: |
          python -m scraping fukuoka_convinient --skip-spreadsheet

      - name: Pull main branch
        run: |
          git fetch origin
          git checkout main
          git pull

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add scraping/data/*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CSV data"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
